### ISSUE TITLE
No tests for the Sessions controller?

### ISSUE THREAD

**Issue by evan-007** [everydayrails/rspec_rails_4#55]
Hi! I'm really enjoying the book, but am wondering why you chose to leave out tests for the sessions controller (unless I'm missing something..)? Are they better tested by feature specs? 

I'm curious because I have an app that uses the same sessions controller as the app for this book and I am trying to think of a way to test #create and #delete. 

cheers

**Comment by ruralocity** [comment]
I prefer to test the session controller with features. Generally speaking, in practice I tend to avoid controller tests unless (a) the controller is doing something outside of the normal CRUD-type stuff, and (b) that functionality isn't easily factored out of the controller.

That said, I spent a lot of time in controllers in the book because they're a good place to demonstrate a lot of techniques, and I did a lot of testing at this level as I was learning myself.
